### ISSUE TITLE
DataFlair Image Processing (24/08)

### ISSUE THREAD

**Issue by E-Roderick** [tj-heat/signed-explorations#1]
## Description

Completion of a codebase to create hand images, a model based on test data, and a live prediction system. Based on [Dataflair](https://data-flair.training/blogs/sign-language-recognition-python-ml-opencv/) implementation. 

This is an important task as the use of camera image capturing will be used to some extent in the finalised game model. Training techniques and model design will be subject to change. The live prediction system will also be used to inform the game model features.

## Tasks

- [x] Initial image capturing.
- [x] Initial model creation.
- [x] Initial live prediction.
- [x] Code reformatting.
- [x] Data utilities/tools.
- [x] Model improvements.

## Requirements

None.

**Comment by E-Roderick** [comment]
Should we add a label for non-identifiable hand signs?

**Comment by E-Roderick** [comment]
Finished all tasks. Code could likely be better but it's good enough.
