### ISSUE TITLE
Character design (30/08)

### ISSUE THREAD

**Issue by HannahHinckfuss** [tj-heat/signed-explorations#10]
# **Description**
There are two characters in the game. The playable main character and NPC. Both require simple sprites to represent them in the game, to accurately connect them with the overarching story, and so players can see their actions played out. The main character is a wizard cat, and the NPC is a dog. The cat has two states, dead and alive. The dead/ghost version of the cat is the main depiction of the main character within the game. The alive version is only shown on the win screen, once the cat has been resurrected.

All characters will be 32x32pixels. To be drawn in a simple pixel style with a 1 pixel width border (not in black but darker main colour).

## SubFeature/component (optional)
Cat
- dead sprite (4 directions = up, down, left, right)
- alive sprite

Dog
- sprite (4 directions = up, down, left, right)
- static dancing with party hat
# **Milestones**
- [x] Inspiration collection (Aug. 19)
- [x] Concept art (Aug. 21)
- [x] Rough Drafts (Aug. 26)
  - [x] Cat Up Rough Draft (Aug. 24)
  - [x] Cat Down Rough Draft (Aug. 24)
  - [x] Cat Side Rough Draft (Aug. 24)
  - [x] Dog Up Rough Draft (Aug. 24)
  - [x] Dog Down Rough Draft (Aug. 24)
  - [x] Dog Side Rough Draft (Aug. 24)
- [x] MVP Final Sprites (Aug. 29)

**Completion Deadline:** Aug. 30

# **Extras (optional)**
- [ ] Animation if time permits
- [ ] Cat Alive 
- [ ] Dog Party

# **Documentation**
- To be put in

# **Members**
- Hannah (@HannahHinckfuss )
