### ISSUE TITLE
MVP Level Design (30/08)

### ISSUE THREAD

**Issue by HannahHinckfuss** [tj-heat/signed-explorations#11]
# **Description**
This feature ticket is focused on the creation of tiles to establish a singular environment, underground catacombs. In the story, the wizard cat has been defeated and must be resurrected. For this to occur the cat and dog must reach the inner chamber which is blocked by a series of puzzles. They must work together to solve those puzzles.

The environment for the MVP should be 25 tiles x 25 tiles. The perspective will be top down/2.5D.

## SubFeature/component (optional)
Intractable tile
- Door/gate (Hannah)
- Light source (Hannah)
- Key (Hannah)

Non-interactable tile
- Stone Brick (Adi)
- Cracked Stone (Adi)
- Water (Adi)
- Wood (Hannah)
- Mossy stone (Adi)

# **Milestones**
- [x] Inspiration collection (Aug. 19)
- [x] Concept art (Aug. 21)
- [x] Rough Draft of Map Layout (Aug. 24)
- [x] Final Design of Map Layout (Aug. 26)
- [x] Rough Drafts of all tile blocks (Aug. 27)
- [x] Final of all tile blocks (Aug. 29)

**Completion Deadline:** Aug. 30

# **Documentation**
- To be put in

# **Members**
- Hannah (@HannahHinckfuss )
- Adi (@Airo1011 )
