### ISSUE TITLE
MVP Presentation Prep (29/08)

### ISSUE THREAD

**Issue by E-Roderick** [tj-heat/signed-explorations#13]
## Description

The MVP Presentation is a five minute presentation discussing SoW details and additional technical work up to the presentation date.

The presentation should have a minimal number of speakers. Current ideas include @Josephjmet for technical details.

The presentation will open to a five minute question period. All members should be familiar with all project facets for answering.

## Tasks

- [x] Confirm SoW contents (24/08)
- [x] Confirm speaker(s) (28/08)
- [x] Create script (29/08)
- [x] Create assisting materials (visuals) (29/08)
- [x] Familiarise full team with content (for questions or missing presenter) (29/08)

### Hard Requirements

- SoW

### Soft Requirements

- Presentation will update on work completed, so no hard requirements.

**Comment by E-Roderick** [comment]
@E-Roderick @tomwebber4398 @Airo1011 @HannahHinckfuss @Josephjmet Need to confirm speakers. Can update assignees after this.
