### ISSUE TITLE
Puzzle UI development

### ISSUE THREAD

**Issue by tomwebber4398** [tj-heat/signed-explorations#15]
### Overview
Tutorial after player interacts with companion pressing e. UI in-game to reflect the camera of the user signing in real life. UI with a reference point for what the user is required to sign.

### Task breakdown
**Puzzle UI designed**
How will the user know how to progress through the level? How will they know how to/when to interact with puzzle elements? The user will have a pop-up when they get close to an interactive puzzle element ‘Press E to [interact]’.  The word in brackets will change depending on the situation e.g. ‘[view]’, ‘[meow]’. There are some tasks that the cat can do but dog can’t do, and some that the cat can’t do but dog can. For example, the cat can sign to unlock doors and such and the dog can interact with physical objects in the work. The meow mechanic (press ‘e’ to call dog over).

**Puzzle interface implemented**
@Josephjmet Can you add to this?

**Puzzle complete feedback (i.e. correct spelling lights up, separate to level complete)**
In the interface, it should be clear when the user has finished signing a word.

**Camera must be incorporated into the UI**
Users should see the camera to ensure they are signing the right letter.

### Project Plan
- [x] Camera must be incorporated into the UI
- [x] Rough Puzzle interface (fingerspelling) designed
- [x]  Final Puzzle interface (fingerspelling) designed
- [x] Puzzle interface implemented
- [x] Puzzle complete feedback (i.e. correct spelling lights up, sound plays etc. separate to level complete)
- [x] User testing

**Out of Scope**
- Multiple items
- Overlay
- Animation, showing/hiding UI elements

**Comment by HannahHinckfuss** [comment]
You press E which calls the dog over, the dog will then look at you asking what you want it to do. If there are multiple things the dog can do he will wait for you to ask.

The dog communicates through body language (like Pokemon HG, SS).

Cat is scared of dark. Needs dog to go through the dark with his toy, find the toy beforehand.
