### ISSUE TITLE
AUSLAN fingerspelling reference design

### ISSUE THREAD

**Issue by tomwebber4398** [tj-heat/signed-explorations#17]
### Overview
In game reference to fingerspelling needs to be available. UI element created (icon that extends maybe a drawer?) with finger spelling references. _Stretch goal: Players are able to unlock different finger spelling as they progress the game. Some are greyed out (similar to WoW sepulcher of the first ones or Skyrim)_

### Task breakdown
**Fingerspelling reference designed**
If a user forgets a particular sign they need to be able to access this knowledge. Consequently, they must be able to learn and note down this knowledge in the game. This knowledge/the learned signs can be accessed via a guide book. It will be picked up at the start of the game. Users can access the book by pressing ‘I’.
- In the book, it should show both the camera angle and your angle.

- [x] Rough UI flow created
- [x] Fingerspelling graphics created
- [x] Final fingerspelling reference guide created

**Comment by tomwebber4398** [comment]
It is a spellbook

**Comment by E-Roderick** [comment]
Having the reference contain both images from the camera's perspective and the player's perspective would help with clarity in what to sign. It would also help the player understand the front/back of the signs.
