### ISSUE TITLE
Pad Model Training Data

### ISSUE THREAD

**Issue by E-Roderick** [tj-heat/signed-explorations#20]
## Description

The current models for gesture recognition are based on a single sample set of ~1600 images. This is not nearly enough, and additional images should be added to improve robustness. Additionally, the current model is trained in ideal conditions, so training in non-ideal conditions would be benficial

Finally, the current training process involves image augmentation to increase the training set. This may be harmful if the generated images do not match live data (shifting and zooming, with `same` pixel reconstruction). As such, it might warrant investigation.

## Tasks

- [x] Generate training images from an additional session.
- [ ] Generate even more training images, ensuring at least one has coverage in a poorly set up environ.
- [ ] Confirm effect of `DataImageGenerator` in model training.

## Requirements

- Partial completion of #1 for data generation framework.

**Comment by E-Roderick** [comment]
@Josephjmet might need input for final task.

**Comment by E-Roderick** [comment]
Generated a new set of data. Did not do Y, as I am unsure of which direction to hold hand. @HannahHinckfuss If you could check [these images](https://github.com/tj-heat/sl-learning/tree/main/data_flair/data/check), that would be great.

**Comment by E-Roderick** [comment]
Changed to ongoing goal, rather than set deadline. Dataset should be padded progressively. Ideally, once per week.

**Comment by E-Roderick** [comment]
Confirmed with @HannahHinckfuss that the new dataset is acceptable. Will need to remove old 'Y' dataset and recreate.

**Comment by E-Roderick** [comment]
Understanding of images is that mirroring is acceptable and gives left/right handed variations. 'Y' images should be 'Y' from signers perspective.

**Comment by E-Roderick** [comment]
Just remembered that I never actually implemented non-max contour discard, so our current training images could be quite noisy. @Josephjmet do you think we should add this ASAP?
