### ISSUE TITLE
Final Submission

### ISSUE THREAD

**Issue by Airo1011** [tj-heat/signed-explorations#45]
## Details

Requirement for the final submission.

## Components

- [x] One Page README and Zipped Codebase
- [x] Include references to Code Support
- [x] Kick Starter Video
- [x] Technical Report (Follow the list of 7)
- [x] Bill of Material
- [ ] Prepare for Expo (Badges, Posters and Aesthetics)

## Milestones

- [x] Rough draft of report content - 09/09/22

**Comment by E-Roderick** [comment]
Updated to add rough draft milestone of 09/09/22
