### ISSUE TITLE
UI Develop - Interactable Notifier ("Press 'E'")

### ISSUE THREAD

**Issue by E-Roderick** [tj-heat/signed-explorations#48]
## Description

Add a notifier for when the player is near an interactable entity. Currently this should be a floating image showing the interact key 'E'.

## Tasks

- [x] Creation of the interaction symbol.
- [x] Display of interaction symbol.
- [x] Detection of when near an interactable.

**Comment by E-Roderick** [comment]
Possible completion of final task. Currently works for items but can be swapped/added to any other type of entity if needed.
