### ISSUE TITLE
Game Dialogue Creation

### ISSUE THREAD

**Issue by E-Roderick** [tj-heat/signed-explorations#52]
## Description

Creation and ideation relating to the dialogue shown in game. This dialogue should cover key instructions to the player, helpful instructions to inform the player of actions the game is about to take, and flavour text for exploring and interacting with objects.

## Tasks

- [x] Creation of key tutorial dialogue (How does the player play the game?)
- [ ] Creation of dialogue informing the player of game actions (E.g. transitioning to/.from camera screen)
- [x] Creation of flavour and interaction text (Provides more world information)
- [x] Creation of introductory lore messages to inform the player of the world.

## Dependencies

- #14
- #19 
- #46 

## Assignees

- @tomwebber4398

**Comment by E-Roderick** [comment]
#19 Contents:
Discovery: What do we want to put at the beginning of the game? Provide a story background? Animation? Text? Still image art?

**Comment by E-Roderick** [comment]
#14 Contents:

Tutorial instruction for game controls e.g. WASD to move, E to interact/meow.

Meow: will bring the companion to the playable character where you can interact with them if close to an interactive object.

Acceptance Criteria: 
1. In game pop-over/modal with control instruction.
2. Press ok to continue
3. User clearly understands controls.


![Image](https://user-images.githubusercontent.com/30396497/186322395-6b9f1e6d-ff81-445e-8319-56d23d2f6da8.jpg)

- [x] Popover design created
- [x] Meow Onomatopoeia created
- [x] Window opens and closes in game
- [ ] Companion Interactive

**Comment by E-Roderick** [comment]
Unsure of start of bridge dialogue in context of game flow

**Comment by Airo1011** [comment]
Dialouge
